import { Location, Vines, Vineyard, VineyardInfo } from '@/models/types/db';
import Joi from 'joi';

const locationSchema = Joi.object<Location>({
  map: Joi.array()
    .items(
      Joi.object({
        lat: Joi.number().optional(),
        lng: Joi.number().optional(),
      })
    )
    .optional(),
  surface: Joi.number().precision(2).optional(),
  city: Joi.string().optional().allow(''),
  country: Joi.string().optional().allow(''),
  elevation: Joi.number().precision(2).optional(),
  orientation: Joi.string().optional().allow(''),
});

const vinesSchema = Joi.object<Vines>({
  yearOfPlantation: Joi.number().optional(),
  plantingScheme: Joi.object({
    spacing: Joi.number().precision(2).optional(),
    rowOrientation: Joi.string().optional().allow(''),
    density: Joi.number().precision(2).optional(),
    trellisSystem: Joi.boolean().optional(),
  }),
  soilType: Joi.string().optional().allow(''),
  sunlightHours: Joi.number().precision(2).optional(),
});

const vineyardCertificationsSchema = Joi.object({
  eco: Joi.object({
    active: Joi.boolean().optional(),
    fileUrl: Joi.string().optional().allow(''),
  }),
  igp: Joi.object({
    active: Joi.boolean().optional(),
    fileUrl: Joi.string().optional().allow(''),
  }),
  dop: Joi.object({
    active: Joi.boolean().optional(),
    fileUrl: Joi.string().optional().allow(''),
  }),
});

const vineyardInfoSchema = Joi.object<VineyardInfo>({
  location: locationSchema,
  vines: vinesSchema,
  certifications: vineyardCertificationsSchema,
});

const vineyardGrapeSchema = Joi.object({
  id: Joi.string().optional().allow(''),
  clonalSelection: Joi.string().optional().allow(''),
  vivcNumber: Joi.string().optional().allow(''),
  countryOfOrigin: Joi.string().optional().allow(''),
});

export const vineyardSchema = Joi.object<Vineyard>({
  id: Joi.string().required(), // * Autogenerated
  name: Joi.string().required(), // * Input by user in form
  grapeVariety: Joi.string().required(), // * Input by user in form
  grapeColor: Joi.string().required(), // * Input by user in form
  cadastralNumber: Joi.string().optional().allow(''),
  info: vineyardInfoSchema,
  grape: vineyardGrapeSchema.optional(),
  status: Joi.string().optional(), // * Input by user in form
  forecastedYield: Joi.number().precision(2).optional(), // * Autogenerated
  labData: Joi.object({
    id: Joi.string().optional().allow(''),
    fileUrl: Joi.string().optional().allow(''),
    items: Joi.array()
      .items(
        Joi.object({
          id: Joi.string().optional().allow(''),
          name: Joi.string().optional().allow(''),
          value: Joi.number().precision(2).optional(),
          variation: Joi.number().precision(2).optional(),
          unit: Joi.string().optional().allow(''),
          responsible: Joi.object({
            name: Joi.string().optional().allow(''),
            email: Joi.string().optional().allow(''),
          }),
        })
      )
      .optional(),
    date: Joi.string().optional().allow(''),
  }).optional(),
  tasks: Joi.array() // * Autogenerated
    .items(
      Joi.object({
        id: Joi.string().optional().allow(''),
        status: Joi.string().optional().allow(''),
        amount: Joi.number().optional(),
      })
    )
    .optional(),
  notes: Joi.array() // * Autogenerated
    .items(
      Joi.object({
        id: Joi.string().optional().allow(''),
        title: Joi.string().optional().allow(''),
        content: Joi.string().optional().allow(''),
      })
    )
    .optional(),
  documents: Joi.array().items(
    Joi.object({
      id: Joi.string().optional().allow(''),
      name: Joi.string().optional().allow(''),
      fileUrl: Joi.string().optional().allow(''),
      owner: Joi.object({
        name: Joi.string().optional().allow(''),
        email: Joi.string().optional().allow(''),
      }),
      uploadDate: Joi.string().optional().allow(''),
      media: Joi.object({
        type: Joi.string().optional().allow(''),
        subtype: Joi.string().optional().allow(''),
        sizeMb: Joi.number().precision(2).optional(),
      }),
    })
  ),
  group: Joi.string().optional().allow(''),
});
