"use strict";

import { Location, Vines, Vineyard, VineyardInfo } from "@/models/types/db";
import { Timestamp } from "firebase/firestore";
import Joi from "joi";

const locationSchema = Joi.object<Location>({
  map: Joi.array()
    .items(
      Joi.object({
        lat: Joi.number().optional(),
        lng: Joi.number().optional(),
      })
    )
    .optional(),
  surface: Joi.number().empty("").default(1),
  city: Joi.string().optional().allow(""),
  country: Joi.string().optional().allow(""),
  elevation: Joi.number().empty("").default(1),
  orientation: Joi.string().optional().allow(""),
});

const vinesSchema = Joi.object<Vines>({
  yearOfPlantation: Joi.number().empty("").default(1900),
  plantingScheme: Joi.object({
    spacing: Joi.number().empty("").default(1),
    rowOrientation: Joi.string().optional().allow(""),
    density: Joi.number().empty("").default(1),
    trellisSystem: Joi.boolean().optional(),
    plantsPerHa: Joi.number().empty("").default(1).optional(),
  }),
  soilType: Joi.string().optional().allow(""),
  sunlightHours: Joi.number().empty("").default(1),
});

const vineyardCertificationsSchema = Joi.object({
  eco: Joi.object({
    active: Joi.boolean().optional(),
    fileUrl: Joi.string().optional().allow(""),
  }),
  igp: Joi.object({
    active: Joi.boolean().optional(),
    fileUrl: Joi.string().optional().allow(""),
  }),
  dop: Joi.object({
    active: Joi.boolean().optional(),
    fileUrl: Joi.string().optional().allow(""),
  }),
});

const vineyardInfoSchema = Joi.object<VineyardInfo>({
  location: locationSchema,
  vines: vinesSchema,
  certifications: vineyardCertificationsSchema,
});

const vineyardGrapeSchema = Joi.object({
  id: Joi.string().optional().allow(""),
  clonalSelection: Joi.string().optional().allow(""),
  vivcNumber: Joi.string().optional().allow(""),
  countryOfOrigin: Joi.string().optional().allow(""),
});

const labDataSchema = Joi.object({
  id: Joi.string().optional().allow(""),
  fileUrl: Joi.string().optional().allow(""),
  items: Joi.array()
    .items(
      Joi.object({
        id: Joi.string().optional().allow(""),
        name: Joi.string().optional().allow(""),
        value: Joi.number().precision(2).optional(),
        variation: Joi.number().precision(2).optional(),
        unit: Joi.string().optional().allow(""),
        responsible: Joi.object({
          name: Joi.string().optional().allow(""),
          email: Joi.string().optional().allow(""),
        }),
        date: Joi.string().optional().allow(""),
      })
    )
    .optional(),
  date: Joi.string().optional().allow(""),
}).optional();

const TimestampOrString = Joi.alternatives().try(
  Joi.string().isoDate(),
  Joi.object().custom((value, helpers) => {
    if (value instanceof Timestamp) return value;
    return helpers.error("any.invalid");
  }, "Timestamp validation")
);

export const actionRelationSchema = Joi.array()
  .items(
    Joi.object({
      id: Joi.string().optional().allow(""),
      name: Joi.string().optional().allow(""),
    })
  )
  .optional();

export const vineyardSchema = Joi.object<Vineyard>().keys({
  id: Joi.string().required(), // * Autogenerated
  name: Joi.string().required(), // * Input by user in form
  grapeVariety: Joi.string().required(), // * Input by user in form
  grapeColor: Joi.string().required(), // * Input by user in form
  cadastralNumber: Joi.string().optional().allow(""),
  rowType: Joi.string().optional(),
  info: vineyardInfoSchema,
  grape: vineyardGrapeSchema.optional(),
  status: Joi.string().optional(), // * Input by user in form
  forecastedYield: Joi.number().empty("").default(1),
  tasks: Joi.array() // * Autogenerated
    .items(
      Joi.object({
        id: Joi.string().optional().allow(""),
        status: Joi.string().optional().allow(""),
        amount: Joi.number().optional(),
      })
    )
    .optional(),
  notes: Joi.array() // * Autogenerated
    .items(
      Joi.object({
        id: Joi.string().optional().allow(""),
        title: Joi.string().optional().allow(""),
        content: Joi.string().optional().allow(""),
      })
    )
    .optional(),
  documents: Joi.array().items(
    Joi.object({
      id: Joi.string().optional().allow(""),
      name: Joi.string().optional().allow(""),
      fileUrl: Joi.string().optional().allow(""),
      owner: Joi.object({
        name: Joi.string().optional().allow(""),
        email: Joi.string().optional().allow(""),
      }),
      uploadDate: Joi.string().optional().allow(""),
      media: Joi.object({
        type: Joi.string().optional().allow(""),
        subtype: Joi.string().optional().allow(""),
        sizeMb: Joi.number().precision(2).optional(),
      }),
    })
  ),
  group: Joi.array().items(Joi.string().optional().allow("")),
  createdAt: TimestampOrString.empty("").optional(),
  actions: actionRelationSchema,
  batches: actionRelationSchema,
  labData: actionRelationSchema,
});
