import type { IFile } from "./fileUtils";

export const DATA: IFile[] = [
  {
    entry: {
      location1: "Hidden location",
      status: "Some status",
      date1: "May 21 2017",
    },
    id: "111",
    group: ["TEST ENTRY"],
    rowType: "item",
    dateModified: "May 23 2025",
    location: "LOCATION 2",
    size: 1,
  },
  {
    entry: {
      status: "Some status",
      date1: "May 21 2017",
      location1: "Hidden location",
    },
    id: "112",
    group: ["WHATS UP WITH ME?!"],
    rowType: "item",
    dateModified: "May 22 2025",
    location: "LOCATION 1",
    size: 0.1234,
  },
  { id: "1", group: ["Documents"], rowType: "group" },
  { id: "2", group: ["Documents", "txt"], rowType: "group" },
  {
    id: "3",
    group: ["Documents", "txt", "notes.txt"],
    rowType: "item",
    location: "location 1",
    dateModified: "May 21 2017",
    size: 14.7,
    /*entry: {
        status: "Some status",
      },*/
  },
  { id: "4", group: ["Documents", "pdf"], rowType: "group" },
  {
    id: "5",
    group: ["Documents", "pdf", "book.pdf"],
    rowType: "item",
    location: "location 2",
    dateModified: "May 22 2025",
    size: 2.1,
  },
  {
    id: "6",
    group: ["Documents", "pdf", "cv.pdf"],
    rowType: "item",
    location: "location 1",
    dateModified: "May 20 2016",
    size: 2.4,
  },
  { id: "7", group: ["Documents", "xls"], rowType: "group" },
  {
    id: "8",
    group: ["Documents", "xls", "accounts.xls"],
    rowType: "item",
    location: "location 2",
    dateModified: "May 22 2025",
    size: 4.3,
  },
  { id: "9", group: ["Documents", "stuff"], rowType: "group" },
  {
    id: "10",
    group: ["Documents", "stuff", "xyz.txt"],
    rowType: "item",
    location: "location 2",
    dateModified: "Jan 17 2016",
    size: 1.1,
  },
  { id: "11", group: ["Music"], rowType: "group" },
  { id: "12", group: ["Music", "mp3"], rowType: "group" },
  {
    id: "13",
    group: ["Music", "mp3", "theme.mp3 (empty location & date)"],
    rowType: "item",
    //location: "",
    //dateModified: "",
    size: 14.3,
  },
  { id: "14", group: ["Misc"], rowType: "group" },
  {
    id: "15",
    group: ["Misc", "temp.txt (no location)"],
    rowType: "item",
    dateModified: "Aug 12 2016",
    size: 101,
  },
];
